"""constraint"""

# YOLO Model
YOLO_PADDING_VALUE = 114
YOLO_DEFAULT_CONF_THRESHOLD = 0.01  # Match training threshold
YOLO_DEFAULT_IOU_THRESHOLD = 0.45
YOLO_TIGHT_IOU_THRESHOLD = 0.3
YOLO_EDGE_WEIGHT_MULTIPLIER = 0.5
YOLO_BORDER_DISTANCE_ALPHA = 0.5

# Tile Loading
DEFAULT_TILE_SIZE = 256
MAX_TILE_CACHE_SIZE = 1600
DEFAULT_THREAD_COUNT = 32
TILE_LOAD_DEBOUNCE_MS = 5
TILE_BATCH_SIZE = 12
TILE_BATCH_INTERVAL_MS = 8
TILE_CACHE_CLEANUP_PERCENT = 0.2

# Normalisasi Gambar
PERCENTILE_LOW = 2
PERCENTILE_HIGH = 98
UINT16_MAX_VALUE = 65535
UINT8_MAX_VALUE = 255
MID_GRAY_VALUE = 128
NORMALIZED_COORD_THRESHOLD = 1.01
REFLECTANCE_MAX_THRESHOLD = 1.0
REFLECTANCE_MIN_THRESHOLD = 0.0
NORMALIZED_RANGE_THRESHOLD = 1.5

# Geospasial
EARTH_RADIUS_METERS = 6371000
METERS_PER_DEGREE = 111320.0
MIN_DETERMINANT_THRESHOLD = 1e-20
EPSG_WGS84 = 4326

# Transformasi Koordinat
MAX_IMAGE_CHANNELS = 8
MIN_IMAGE_DIMENSION = 1
TRANSPOSED_FEATURE_THRESHOLD = 100
TRANSPOSED_DETECTION_THRESHOLD = 1000

# Pipeline Deteksi
MIN_YOLO_FEATURES = 5
YOLO_X1_IDX = 0
YOLO_Y1_IDX = 1
YOLO_X2_IDX = 2
YOLO_Y2_IDX = 3
YOLO_CONF_IDX = 4
YOLO_CLASS_IDX = 5
NUM_COORDS_PER_DETECTION = 4
MAX_SAMPLE_DETECTIONS_LOG = 3
MAX_COORD_TRANSFORM_LOGS = 3

# Performance
EPSILON = 1e-12
ZERO_THRESHOLD = 0
MAX_OUTPUT_LINES = 30000
